services:
  tests:
    build: .
    container_name: tasks_tests
    volumes:
      - .:/app
    depends_on:
      - db
    command: ruff check . && pytest
  migration:
    build: .
    command: alembic upgrade head
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/tareas
    depends_on:
      db:
        condition: service_started
  api:
    build: .
    container_name: tasks_api
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/tareas
    depends_on:
      db:
        condition: service_started
      tests:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
  db:
    image: postgres:15
    container_name: data_base
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tareas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data:            