"""empty message

Revision ID: abb9c2d47873
Revises: 
Create Date: 2026-09-22 22:15:31.411564

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'abb9c2d47873'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
